name: Cloudflare Pages Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # <-- あなたのアカウントID
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: takum1-me # <-- あなたのプロジェクト名
          directory: dist
          branch: ${{ github.head_ref }}

      - name: Post preview URL to PR
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PREVIEW_URL=$(echo '${{ steps.deploy.outputs.url }}' | sed 's/https:\/\///')
          PREVIEW_URL_ESCAPED=$(echo $PREVIEW_URL | sed -e 's/&/%26/g')

          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
            -d "{ \"body\": \"✨ **Preview URL:** https://${PREVIEW_URL_ESCAPED} \" }"
